apiVersion: apps/v1
kind: Deployment
metadata:
  name: csweb-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    app: csweb-{{ default "staging" .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csweb-{{ default "staging" .Release.Namespace }}
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: csweb-{{ default "staging" .Release.Namespace }}
        {{ if ne .Release.Namespace "production" }}name: csweb-{{ .Release.Namespace }}{{- else }}hostname: csweb{{- end }}
    spec:
      {{ if ne .Release.Namespace "production" }}hostname: csweb-{{ .Release.Namespace }}{{- else }}hostname: csweb{{- end }} 
      dnsPolicy: Default
      dnsConfig:
        searches:
          - cs.calvin.edu
      containers:
      - name: csweb-{{ default "staging" .Release.Namespace }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 22
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m" #0.1 CPU
          limits:
            memory: "300Mi"
            cpu: "250m" #0.25 CPU
        volumeMounts:
        - mountPath: /home
          name: mount0
        - mountPath: /var/www
          name: mount1
        - mountPath: /opt/passwd
          name: mount2
      volumes:
      - name: mount0
        nfs:
          path: /export/home
          server: aznfs-int.cs.calvin.edu
      - name: mount1
        persistentVolumeClaim:
          claimName: pvc-csweb-nfs-{{ default "staging" .Release.Namespace }}
      - name: mount2
        nfs:
          path: /export/passwd
          server: aznfs-int.cs.calvin.edu
---
apiVersion: v1
kind: Service
metadata:
  name: csweb-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: csweb{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    service.beta.kubernetes.io/azure-dns-label-name: calvincs-csweb{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
    name: ssh
    protocol: TCP
  selector:
    app: csweb-{{ default "staging" .Release.Namespace }}
---
# {{ if eq .Release.Namespace "production" }}
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: csweb-{{ default "staging" .Release.Namespace }}
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: csweb-{{ default "staging" .Release.Namespace }}
#   minReplicas: 1
#   maxReplicas: 3
#   targetCPUUtilizationPercentage: 80
#   #metrics:
#   #- type: Resource
#   #  resource:
#   #    name: cpu
#   #    target:
#   #      type: Utilization
#   #      averageUtilization: 80
#   #- type: Resource
#   #  resource:
#   #    name: memory
#   #    target:
#   #      type: Utilization
#   #      averageUtilization: 85
# {{- end }}
