apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cswebnfs-csweb-rw-{{ default "staging" .Release.Namespace }}
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - soft
    - relatime
    - vers=4.1
    - namlen=255
    - proto=tcp
    - timeo=600
    - retrans=2
    - sec=sys
  nfs:
    path: /calvincsaks/csweb
    server: calvincsaks.file.core.windows.net
---
# Source: csweb/templates/csweb-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cswebnfs-csweb-rw-{{ default "staging" .Release.Namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
