apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-csweb-nfs-{{ default "staging" .Release.Namespace }}
spec:
  capacity:
    storage: 98Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - soft
    - relatime
    - vers=3
    - namlen=255
    - proto=tcp
    - timeo=600
    - retrans=2
    - sec=sys
  nfs:
    path: /exports/csweb
    server: cswebnfs-int.k8s.cs.calvin.edu
---
# Source: csweb/templates/csweb-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csweb-nfs-{{ default "staging" .Release.Namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 98Gi
