name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/csweb:latest
          push: true
          secrets: |
            CSWEB_SSH_HOST_ECDSA_KEY=${{ secrets.CSWEB_SSH_HOST_ECDSA_KEY }}
            CSWEB_SSH_HOST_ECDSA_KEY_PUB=${{ secrets.CSWEB_SSH_HOST_ECDSA_KEY_PUB }}
            CSWEB_SSH_HOST_ED25519_KEY=${{ secrets.CSWEB_SSH_HOST_ED25519_KEY }}
            CSWEB_SSH_HOST_ED25519_KEY_PUB=${{ secrets.CSWEB_SSH_HOST_ED25519_KEY_PUB }}
            CSWEB_SSH_HOST_RSA_KEY=${{ secrets.CSWEB_SSH_HOST_RSA_KEY }}
            CSWEB_SSH_HOST_RSA_KEY_PUB=${{ secrets.CSWEB_SSH_HOST_RSA_KEY_PUB }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image

    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: latest
      - name: Set AKS login information
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace staging \
            csweb \
            ./kubernetes/csweb \
            --set image.repository=${{ secrets.ACR_NAME }}
